# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4951a249c2dad5150375e980b19f1cc268c70a1d7d118623749db2e6aa53ef6999751b9b44c2a8366f8c86d4efb47cc2e9ecfa58a64768a8147ad15b00f86b

test:
  secret_key_base: 9323eeeb4fd3251ee802e3771e9a7880a743c0a82c440c146ba6ff4a91db49dc544fd4235b5322cdfa6caff714c1a6958ba65ebcb74e417dc980c1a2aa1d2e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
